# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec5b4402963862ef6090028cd32e5a38851dba1589246ec9c4be92522144d22e2c238e15421d90804c1652fb6f20fe1493868fe21689e693773639ee3e8abccd

test:
  secret_key_base: cad2dc59a90976ae51a1dd33618256c8b29bcd48cc36cb70aec92c6cd86fa5c9f114e36a0db2ec2d004b02af08f521cff22241de0a6a312ee05112820e26e3b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
